---
title: "National"
author: "Paddy Adams"
date: "24/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(sf)
library(rgdal)
library(broom)
library(jsonlite)
library(httr)
library(leaflet)
library(spdplyr)
library(sf)
library(proj4)




```



```{r}

# this is the same wrangling as on demographics rmd
# with a couple of tweaks to allow for joining by name
# not just area_code

# I have made an 'area' column in each with area name but 
# it may not be used

ref <- read.csv("~/gov1005-Project/data/EU-referendum-result-data.csv") %>% 
  clean_names() %>% 
  remove_empty() %>% 
  select(area, area_code, pct_leave)

# EMPLOYMENT

employment <- read_excel("~/gov1005-Project/data/Employment_pct.xls", skip = 11) %>% 
  clean_names() %>% 
  remove_empty() %>%
  unite(., col = "area", 2:4, sep = "", remove = TRUE, na.rm = TRUE) 
  
colnames(employment)[7] <- "Unemployed"


employment <- employment %>% 
  select(area_code, Unemployed)

join <- ref %>% 
  left_join(employment, by = "area_code") 

        
# AGE
        
age <- read_excel("~/gov1005-Project/data/age_data.xls", skip = 11) %>% 
    clean_names() %>% 
    remove_empty() %>% 
    unite(., col = "area", 2:4, sep = "", remove = TRUE, na.rm = TRUE)

colnames(age)[1] <- "area_code"
colnames(age)[3] <- "total"

i <- 3:19
age[i] <- lapply(age[i], as.numeric)
        
age <- age %>%
    mutate_at(.funs = funs(pct = ./total), .vars = 4:19)
        
age <- age %>% 
    mutate(over50 = (persons_17_pct + persons_18_pct + persons_19_pct + persons_20_pct + 
                              persons_21_pct + persons_22_pct) * 100) %>% 
    mutate(under50 = (persons_10_pct + persons_11_pct + persons_12_pct + persons_13_pct + 
                              persons_14_pct + persons_15_pct + persons_16_pct) * 100) %>% 
    select(area_code, over50, under50) 

join <- join %>% 
  left_join(age, by = "area_code")  
        
        
# DENSITY
        
density <- read_excel("~/gov1005-Project/data/Population density.xls", sheet = 2, skip = 11) %>% 
    clean_names() %>% 
    remove_empty() %>% 
    unite(., col = "area", 2:4, sep = "", remove = TRUE, na.rm = TRUE) 
        
colnames(density)[5] <- "Density"

less_dense <- density %>% 
  select(area_code, Density)

join <- join %>% 
  left_join(less_dense, by = "area_code")
        
# EDUCATION 
        
ed <- read_excel("~/gov1005-Project/data/Education.xls", sheet = 3, skip = 10) %>% 
    clean_names() %>% 
    remove_empty() %>% 
    unite(., col = "area", 2:4, sep = "", remove = TRUE, na.rm = TRUE)    
    
    
colnames(ed)[4] <- "none"
colnames(ed)[6] <- "gcse"
colnames(ed)[8] <- "a_level"
colnames(ed)[9] <- "uni"
        
less_ed <- ed %>% 
  mutate(Education = a_level + uni) %>% 
  select(Education, area_code)

national_ref_join <- join %>% 
  left_join(less_ed, by = "area_code")


        
```



```{r, general election}

# doesnt work unfortunatly as data is at a much more local scale


ge17 <- read_csv("~/gov1005-Project/data/ge2017.csv") %>% 
  clean_names() 

colnames(ge17)[2] <- "area_code"

i <- 16:19
ge17[i] <- lapply(ge17[i], as.numeric)
        
ge17 <- ge17 %>%
  mutate_at(.funs = funs(pct = ./valid_votes), .vars = 16:19)

join_ge <- ref_join %>% 
  inner_join(ge17, by = c("area" = "county_name"))


```


```{r, map, cache=TRUE}

# this is to plot points over uk  
# read in shapefile using sf package. dsn is location of file and layer is name of the .shp file
# inside folder containing shapefiles
ukshp <- sf::st_read(dsn = "/Users/daddyadams/gov1005-Project/data/shapefiles",
                         layer = "Local_Authority_Districts_December_2017_Full_Clipped_Boundaries_in_Great_Britain")

ukshp <-sf::st_transform(ukshp, crs = "+init=epsg:4326")

# set joining levels the same
ukshp$lad17cd <- as.character(ukshp$lad17cd)

# merge shape file with referendum data
ukMap <- ukshp %>%
  left_join(national_ref_join, by = c("lad17cd" = "area_code"))

# write rds file, but comment out so not everytime I run chunk
# saveRDS(ukMap, "ukMap.RDS") 

# Set color palette, other options available
pal <- colorNumeric("viridis", NULL)

# set so tiles are labelled when hovering over map
labels <- paste(ukMap$area, ukMap$Education, sep = ":  ")

# plot 
leaflet(ukMap) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              label = labels, fillColor = ~ pal(Education)) %>%
  addLegend(pal = pal, values = ~ Education, opacity = 1.0)

```



